### ISSUE TITLE
Revitalize project

### ISSUE THREAD

**Issue by guusdk** [javpla/openfire#1]
Hi Javier! I would be interested in using this project to create a new plugin for Openfire, that adds EXI support.

The code isn't necessarily clear on the license under which it is released. There's mention of GPL in the `plugin.xml` file, but that's probably because that was in the old template for that file, ten years ago!

Would you be willing to explicitly mark this repository as using the Apache v2 license? That corresponds with what Openfire is using these days.

**Comment by javpla** [comment]
Sure! I added the apache license file now. Please go ahead and use it 👍

**Comment by guusdk** [comment]
Excellent, thank you!

**Comment by guusdk** [comment]
@javpla I have now created a new repository that holds the source of this project, but rewritten to remove all Openfire artifacts here: https://github.com/igniterealtime/openfire-exi-plugin

I've added license headers to all your original files, and I believe I was successful in retaining all relevant history.

...

Wanna PR? :)
